baseURL = "https://esim.techpawz.com/"
languageCode = "en"
title = "esim"
theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
